# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fffda129ae1fd070ba0bfa9cf9f31232aa8a95a540392070e6f811df445b81d9cadbdba14a1a3768d64afd902713f52cd6d172b37e7112c3ee006ad1de82c4d

test:
  secret_key_base: 96be8b6169b7c0eabca6a4338882c206875935661f2ba2f6a81a060051de22a5c63c02f78dfa36f3cb2631ca269b852b1f4e4373d1735536498cc5d48ade4c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
